name: Build Binaries

on: [push, pull_request]

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Release

jobs:
    build_debian_bullseye:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        
        - name: list folders
          run: ls -alrt

        - name: list folders
          run: ls -alrt $GITHUB_WORKSPACE

        - name: get env
          run: env

        - name: Create Docker Image
          run: cd $GITHUB_WORKSPACE/docker && docker build . --tag sdrpp_build

        - name: Run Container
          run: docker run --name build -v $GITHUB_WORKSPACE:/workdir --env BUILD_NO="-$GITHUB_RUN_NUMBER" sdrpp_build /entrypoint.sh
